# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aarón Villanueva
title: Theoretical Physicist · Quantum Control & Quantum Computing
email: aaronuzv@gmail.com
email_2: aaronv@science.ru.nl
website: https://github.com/aaronuv

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: aaronuv
linkedin_username: aaronuv
orcid_username:

# Additional icon links
additional_links:
  - title: Google Scholar
    icon: fas fa-graduation-cap
    url: https://scholar.google.com/
  - title: arXiv profile
    icon: fas fa-file-alt
    url: https://arxiv.org/
